Repository bcdice/BCDice, pull requests merged in 2019-10, with the labels that each got.

#95 上方無限ロール：負の修正値に対応する
  src/dice/UpperDice.rb
  src/test/data/None.txt
Labels: bug

#96 Call of Cthulhu7版のダイスボットの修正と新機能の実装
  src/diceBot/Cthulhu7th.rb
  src/test/data/Cthulhu7th.txt
Labels: 新機能

#97 サタスペのダイスボットへの使用頻度の高い表の追加
  src/diceBot/Satasupe.rb
  src/test/data/Satasupe.txt
Labels: bug, 新機能

#99 「ダイスボットの作り方」をMarkdown化
  README.md
  docs/how_to_make_dicebot.md
  src/test/README.html
Labels: document

#102 シャドウラン第5版のグリッチ判定の誤りを修正
  src/diceBot/ShadowRun5.rb
  src/test/data/ShadowRun5.txt
Labels: bug

#98 DoubleCross: 成功判定を中心とするリファクタリング
  src/.rubocop_todo.yml
  src/bcdiceCore.rb
  src/dice/RerollDice.rb
  src/diceBot/DiceBot.rb
  src/diceBot/DoubleCross.rb
  src/test/data/DoubleCross.txt
Labels: refactoring

#104 DoubleCross: 正規表現の埋め込みをやめる
  src/diceBot/DoubleCross.rb
Labels: bug

#101 テスト中に表示されるWARNを修正
  src/CardTrader.rb
  src/CountHolder.rb
  src/bcdiceCore.rb
  src/dice/AddDice.rb
  src/diceBot/Airgetlamh.rb
  src/diceBot/Alsetto.rb
  src/diceBot/Avandner.rb
  src/diceBot/BadLife.rb
  src/diceBot/BeastBindTrinity.rb
  src/diceBot/BlindMythos.rb
  src/diceBot/Chill3.rb
  src/diceBot/ColossalHunter.rb
  src/diceBot/DarkBlaze.rb
  src/diceBot/DarkSouls.rb
  src/diceBot/DetatokoSaga.rb
  src/diceBot/DetatokoSaga_Korean.rb
  src/diceBot/DiceBot.rb
  src/diceBot/DiceOfTheDead.rb
  src/diceBot/Dracurouge_Korean.rb
  src/diceBot/EarthDawn.rb
  src/diceBot/EarthDawn3.rb
  src/diceBot/EarthDawn4.rb
  src/diceBot/Elysion.rb
  src/diceBot/EmbryoMachine.rb
  src/diceBot/Gurps.rb
  src/diceBot/GurpsFW.rb
  src/diceBot/Illusio.rb
  src/diceBot/JamesBond.rb
  src/diceBot/LiveraDoll.rb
  src/diceBot/LogHorizon_Korean.rb
  src/diceBot/MeikyuDays.rb
  src/diceBot/MeikyuKingdom.rb
  src/diceBot/Nechronica.rb
  src/diceBot/Nechronica_Korean.rb
  src/diceBot/NightmareHunterDeep.rb
  src/diceBot/OrgaRain.rb
  src/diceBot/Raisondetre.rb
  src/diceBot/Satasupe.rb
  src/diceBot/ShadowRun5.rb
  src/diceBot/Skynauts.rb
  src/diceBot/StrangerOfSwordCity.rb
  src/diceBot/Strave.rb
  src/diceBot/TokumeiTenkousei.rb
  src/diceBot/Torg.rb
  src/diceBot/TrinitySeven.rb
  src/irc/ircBot.rb
Labels: refactoring

#103 シノビガミの表関連をリファクタリング
  src/diceBot/DiceBot.rb
  src/diceBot/ShinobiGami.rb
  src/test/data/ShinobiGami.txt
  src/utils/table.rb
Labels: refactoring
