Repository bcdice/BCDice, pull requests merged in 2020-04, with the labels that each got.

#150 CIで特定のRubyの時だけCodecovを使う
  .travis.yml
  src/test/setup.rb
Labels: CI

#153 AddDice::Parser: テストケースを追加する
  src/test/data/None.txt
Labels: enhance dicebot

#156 AddDice::Node: ノードのS式を返すメソッドを追加する
  Rakefile
  src/dice/add_dice/node.rb
  src/test/add_dice_parser_test.rb
Labels: refactoring, 新機能

#157 AddDice: 定数畳み込み関連のテストケースを追加する
  src/test/data/None.txt
Labels: refactoring

#151 [SwordWorld] レーティング表の半減
  src/diceBot/SwordWorld.rb
  src/diceBot/SwordWorld2_0.rb
  src/diceBot/SwordWorld2_5.rb
  src/test/data/SwordWorld.txt
  src/test/data/SwordWorld2_0.txt
Labels: enhance dicebot

#158 Remove Object#untaint
  src/TableFileData.rb
  src/diceBot/DiceBotLoader.rb
Labels: refactoring

#159 rand_resultsを初期化しておくようにする
  src/bcdiceCore.rb
Labels: refactoring

#160 [ArsMagica] 他のダイスボットの出力形式異なる部分を修正
  src/diceBot/ArsMagica.rb
  src/test/data/ArsMagica.txt
Labels: bug

#161 YearZeroEngine追加
  src/diceBot/YearZeroEngine.rb
  src/test/data/YearZeroEngine.txt
Labels: new dicebot

#162 AddDice::Node: 二項演算子をリファクタリングする
  src/dice/add_dice/node.rb
  src/dice/add_dice/parser.rb
Labels: refactoring

#163 クトゥルフテック：説明文をより具体的にする
  src/diceBot/CthulhuTech.rb
Labels: document

#147 AddDice::Parser
  Rakefile
  src/bcdiceCore.rb
  src/dice/AddDice.rb
  src/dice/add_dice/node.rb
  src/dice/add_dice/parser.rb
  src/dice/add_dice/randomizer.rb
  src/diceBot/CthulhuTech.rb
  src/diceBot/DiceBot.rb
  src/diceBot/Satasupe.rb
  src/test/add_dice_parser_test.rb
  src/test/data/None.txt
  src/test/data/RuneQuest.txt
  src/test/data/dummyBot.txt
Labels: refactoring

#165 クトゥルフテック：リファクタリング
  src/dice/add_dice/randomizer.rb
  src/diceBot/CthulhuTech.rb
  src/diceBot/DiceBot.rb
  src/test/data/CthulhuTech.txt
Labels: refactoring

#167 ArsMagicaで成功失敗判定ができない問題を修正
  src/diceBot/ArsMagica.rb
  src/test/data/ArsMagica.txt
Labels: bug

#168 NightWizardで成功失敗判定ができない問題を修正
  src/diceBot/NightWizard.rb
  src/test/data/NightWizard.txt
Labels: bug

#166 BBNTRPGを追加
  CHANGELOG.md
  src/diceBot/BBN.rb
  src/test/data/BBN.txt
Labels: new dicebot

#164 TORG Eternityダイスボット作成
  src/diceBot/TorgEternity.rb
  src/test/data/TorgEternity.txt
Labels: new dicebot

#171 AddDice: D66が振れない問題を修正する
  src/dice/add_dice/randomizer.rb
  src/test/data/None.txt
Labels: bug

#172 AddDice: ダイスロール結果の文字列をノード側で作る
  src/dice/add_dice/node.rb
  src/dice/add_dice/randomizer.rb
Labels: refactoring
