Repository bcdice/BCDice, pull requests merged in 2020-11, with the labels that each got.

#284 SRSじゃない世界樹の迷宮TRPGに対応
  CHANGELOG.md
  lib/bcdice/base.rb
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/NSSQ.rb
  test/data/NSSQ.toml
Labels: new dicebot

#285 ウォーハンマーRPG第4版に対応
  .rubocop_todo.yml
  CHANGELOG.md
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/Warhammer4.rb
  test/data/Warhammer4.toml
Labels: new dicebot

#292 GURPSのクラス名を修正する
  lib/bcdice/game_system/GURPS.rb
Labels: bug

#301 GURPSのリファクタリング
  lib/bcdice/game_system/GURPS.rb
  test/data/GURPS.toml
Labels: refactoring
