Repository bcdice/BCDice, pull requests merged in 2020-05, with the labels that each got.

#173 加算ダイスの構文解析時に、ダイスロールが含まれるか確認する
  src/dice/add_dice/parser.rb
  src/test/data/None.txt
Labels: bug

#182 BCDice@isMessagePrintedを削除する
  src/bcdiceCore.rb
Labels: refactoring

#180 ダブルクロス：感情表などのリファクタリング
  src/diceBot/DoubleCross.rb
Labels: refactoring

#183 Vampire:the Masquerade5thダイスボット作成
  src/diceBot/VampireTheMasquerade5th.rb
  src/test/data/VampireTheMasquerade5th.txt
Labels: new dicebot

#187 [新クトゥルフTRPG] 誤植修正
  src/diceBot/Cthulhu7th.rb
Labels: bug

#181 加算ロール：フィルタ処理付きダイスロールを追加する
  src/dice/add_dice/node.rb
  src/dice/add_dice/parser.rb
  src/dice/add_dice/randomizer.rb
  src/test/add_dice_parser_test.rb
  src/test/data/None.txt
Labels: 新機能

#184 Paranoia Rebootedダイスボット追加
  src/diceBot/ParanoiaRebooted.rb
  src/test/data/ParanoiaRebooted.txt
Labels: new dicebot

#188 マスターコマンド：レーティング表設定コマンドを削除する
  src/bcdiceCore.rb
  src/diceBot/DiceBot.rb
Labels: bug, refactoring

#193 カードランカーで学園場所表が実行できない問題を修正
  src/diceBot/CardRanker.rb
  src/test/data/CardRanker.txt
Labels: bug

#195 [Cthulhu] 技能ロールの目標値を四則演算で指定
  src/diceBot/Cthulhu.rb
  src/test/data/Cthulhu.txt
Labels: enhance dicebot

#194 フタリソウサの韓国語対応
  src/diceBot/FutariSousa_Korean.rb
  src/test/data/FutariSousa_Korean.txt
Labels: new dicebot

#196 ソード・ワールド2.0/2.5: 威力表の半減（HK）を実行できるようにする
  src/diceBot/SwordWorld.rb
  src/diceBot/SwordWorld2_0.rb
  src/diceBot/SwordWorld2_5.rb
  src/test/data/SwordWorld2_0.txt
  src/test/data/SwordWorld2_5.txt
Labels: bug

#203 サンサーラ・バラッドのダイスボット追加
  src/configBcDice.rb
  src/diceBot/DiceBotLoaderList.rb
  src/diceBot/SamsaraBallad.rb
  src/test/data/SamsaraBallad.txt
Labels: new dicebot

#207 汎用コマンドパーサー
  Rakefile
  src/diceBot/SamsaraBallad.rb
  src/test/data/SamsaraBallad.txt
  src/test/test_command_parser.rb
  src/utils/command_parser.rb
Labels: refactoring

#208 IRCボット：終了コマンドを削除する
  src/bcdice.rb
  src/bcdiceCore.rb
  src/bcdiceGui.rb
  src/configBcDice.rb
  src/irc/encode.rb
  src/irc/ircBot.rb
  src/irc/torgtaitaiIRC.rb
Labels: IRCボット分離独立化
