Repository bcdice/BCDice, pull requests merged in 2020-06, with the labels that each got.

#212 ヘルプコマンドを削除する
  src/CardTrader.rb
  src/bcdiceCore.rb
Labels: IRCボット分離独立化

#209 上方無限ロールのリファクタリング
  .rubocop_todo.yml
  src/bcdiceCore.rb
  src/dice/UpperDice.rb
  src/diceBot/DiceBot.rb
  src/diceBot/RoleMaster.rb
  src/diceBot/ShadowRun.rb
  src/diceBot/_Template.rb
  src/test/data/None.txt
  src/test/data/UpperDice.txt
  src/test/data/dummyBot.txt
  src/utils/format.rb
Labels: refactoring

#216 マスターコマンドを削除する
  src/CardTrader.rb
  src/bcdiceCore.rb
Labels: IRCボット分離独立化

#213 カオスフレアの専用コマンドを追加
  src/diceBot/ChaosFlare.rb
  src/test/data/ChaosFlare.txt
  src/utils/command_parser.rb
Labels: new dicebot

#220 ソード・ワールド2.0：超越判定を特殊コマンド化する
  src/dice/add_dice/node.rb
  src/dice/add_dice/parser.rb
  src/dice/add_dice/randomizer.rb
  src/diceBot/DiceBot.rb
  src/diceBot/SwordWorld2_0.rb
  src/diceBot/SwordWorld2_5.rb
  src/test/data/SwordWorld2_0.txt
  src/test/data/SwordWorld2_5.txt
Labels: refactoring

#221 アニマアニムスのダイスボットを追加
  src/diceBot/AnimaAnimus.rb
  src/test/data/AnimaAnimus.txt
Labels: new dicebot

#222 IDとシステム名の修正
  docs/README.txt
  src/configBcDice.rb
  src/diceBot/AlterRaise.rb
  src/diceBot/Arianrhod.rb
  src/diceBot/BadLife.rb
  src/diceBot/BlindMythos.rb
  src/diceBot/ChaosFlare.rb
  src/diceBot/Chill3.rb
  src/diceBot/Cthulhu.rb
  src/diceBot/Cthulhu7th.rb
  src/diceBot/DeadlineHeroes.rb
  src/diceBot/DiceBotLoader.rb
  src/diceBot/DiceBotLoaderList.rb
  src/diceBot/Elric.rb
  src/diceBot/EmbryoMachine.rb
  src/diceBot/EndBreaker.rb
  src/diceBot/FullMetalPanic.rb
  src/diceBot/GranCrest.rb
  src/diceBot/GundogZero.rb
  src/diceBot/HuntersMoon.rb
  src/diceBot/Illusio.rb
  src/diceBot/LiveraDoll.rb
  src/diceBot/LogHorizon.rb
  src/diceBot/MetallicGuardian.rb
  src/diceBot/MonotoneMuseum.rb
  src/diceBot/NightWizard.rb
  src/diceBot/NightWizard3rd.rb
  src/diceBot/OneWayHeroics.rb
  src/diceBot/OrgaRain.rb
  src/diceBot/Oukahoushin3rd.rb
  src/diceBot/ParasiteBlood.rb
  src/diceBot/PhantasmAdventure.rb
  src/diceBot/Postman.rb
  src/diceBot/RokumonSekai2.rb
  src/diceBot/SRS.rb
  src/diceBot/ShadowRun4.rb
  src/diceBot/ShadowRun5.rb
  src/diceBot/ShinMegamiTenseiKakuseihen.rb
  src/diceBot/ShoujoTenrankai.rb
  src/diceBot/SterileLife.rb
  src/diceBot/SwordWorld.rb
  src/diceBot/TherapieSein.rb
  src/diceBot/TokyoNova.rb
  src/diceBot/TunnelsAndTrolls.rb
  src/diceBot/TwilightGunsmoke.rb
  src/diceBot/WorldOfDarkness.rb
  src/test/data/AlterRaise.txt
  src/test/data/Alter_raise.txt
  src/test/data/ChaosFlare.txt
  src/test/data/Elric.txt
  src/test/data/MetallicGuardian.txt
  src/test/data/TunnelsAndTrolls.txt
  src/test/testDiceBotLoaders.rb
Labels: bug
