Repository bcdice/BCDice, pull requests merged in 2020-12, with the labels that each got.

#313 RerollDice::Nodeをリファクタリングする
  lib/bcdice/common_command/reroll_dice/node.rb
Labels: refactoring

#322 より意図の明確なメソッド（Ruby 2.4以降で使用可能、Array#count）を使う
  lib/bcdice/game_system/CthulhuTech.rb
  lib/bcdice/game_system/DoubleCross.rb
  lib/bcdice/game_system/NinjaSlayer.rb
  lib/bcdice/game_system/SwordWorld.rb
  lib/bcdice/game_system/SwordWorld2_0.rb
  lib/bcdice/game_system/SwordWorld2_5.rb
Labels: refactoring

#324 フィルトウィズ：ナンバーワンくじ、マジカルクッキングをRangeTableで表す
  lib/bcdice/game_system/FilledWith.rb
  lib/bcdice/game_system/filled_with/cook_tables.rb
  lib/bcdice/game_system/filled_with/lot_tables.rb
  test/data/FilledWith.toml
Labels: refactoring

#327 [MagicaLogia] リファクタリング
  lib/bcdice/game_system/MagicaLogia.rb
  test/data/MagicaLogia.toml
Labels: refactoring

#281 アンサング・デュエットに対応
  CHANGELOG.md
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/UnsungDuet.rb
  test/data/UnsungDuet.toml
Labels: new dicebot

#330 [Cthulhu7th] 技能ロールと組み合わせロールのリファクタリング
  lib/bcdice/game_system/Cthulhu7th.rb
  lib/bcdice/game_system/PulpCthulhu.rb
  test/data/Cthulhu7th.toml
  test/data/PulpCthulhu.toml
Labels: refactoring

#335 バラバラロール（xBn）の結果に出目と成功数を加える
  lib/bcdice/common_command/barabara_dice/node.rb
  lib/bcdice/common_command/barabara_dice/result.rb
  lib/bcdice/game_system/NinjaSlayer.rb
  lib/bcdice/result.rb
Labels: refactoring

#336 ダブルクロス：成功/失敗/ファンブルを結果に含める
  lib/bcdice/game_system/DoubleCross.rb
  test/data/DoubleCross.toml
  test/data/DoubleCross_Korean.toml
Labels: enhance dicebot

#337 [AddDice] KH系で要素をカッコ付きにすると動かない問題を修正
  lib/bcdice/common_command/add_dice/node.rb
  test/data/None.toml
  test/test_add_dice_parser.rb
Labels: bug

#345 呪印感染を追加
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/JuinKansen.rb
  test/data/JuinKansen.toml
Labels: new dicebot

#346 [KillDeathBusiness] 修正値が前処理で負数になっても動くように
  CHANGELOG.md
  lib/bcdice/game_system/KillDeathBusiness.rb
  test/data/KillDeathBusiness.toml
Labels: bug

#347 [ShinobiGami] 行為判定コマンド
  CHANGELOG.md
  lib/bcdice/game_system/ShinobiGami.rb
  test/data/ShinobiGami.toml
Labels: enhance dicebot

#348 [Cthulhu7th] 技能判定のボーナスダイス数を100まで緩和する
  lib/bcdice/game_system/Cthulhu7th.rb
  test/data/Cthulhu7th.toml
Labels: enhance dicebot

#354 計算コマンド：入力された数式を出力する
  lib/bcdice/arithmetic/node.rb
  lib/bcdice/common_command/calc/node.rb
  lib/bcdice/common_command/calc/parser.y
  test/data/BloodMoon.toml
  test/data/None.toml
  test/data/Repeat.toml
  test/data/calc.toml
Labels: 新機能

#358 [UpperDice] 修正値の先頭にマイナスを入れると誤った式になるのを修正
  lib/bcdice/common_command/upper_dice/parser.y
  test/data/UpperDice.toml
Labels: bug

#359 [DoubleCross] DXの修正値で `1+-4` となったときに動くように
  lib/bcdice/game_system/DoubleCross.rb
  test/data/DoubleCross.toml
Labels: bug

#360 MagicaLogia_Koreanを追加
  CHANGELOG.md
  i18n/MagicaLogia/ko_kr.yml
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/MagicaLogia.rb
  lib/bcdice/game_system/MagicaLogia_Korean.rb
  test/data/MagicaLogia_Korean.toml
Labels: new dicebot
