Repository bcdice/BCDice, pull requests merged in 2020-03, with the labels that each got.

#124 ダイスボット追加（獸ノ森）
  src/configBcDice.rb
  src/diceBot/KemonoNoMori.rb
  src/test/data/KemonoNoMori.txt
  src/test/testDiceBotLoaders.rb
Labels: new dicebot

#130 Rakefileなどをリポジトリルートに移動する
  .gitignore
  .rubocop.yml
  .rubocop_todo.yml
  .travis.yml
  Gemfile
  Rakefile
  codecov.yml
  src/.gitignore
Labels: refactoring

#136 Ruby 1.9の時だけjson gemのバージョンを指定する
  Gemfile
Labels: refactoring

#132 RangeTable: 範囲指定による表の定義
  Rakefile
  src/diceBot/BattleTech.rb
  src/diceBot/DiceBot.rb
  src/diceBot/KemonoNoMori.rb
  src/diceBot/MetalHead.rb
  src/test/data/BattleTech.txt
  src/test/range_table_test.rb
  src/utils/range_table.rb
Labels: refactoring

#134 Tens D10などの詳細なダイスロール一覧
  Rakefile
  src/bcdiceCore.rb
  src/diceBot/Cthulhu7th.rb
  src/test/test_detailed_rand_results.rb
Labels: 新機能

#140 Extratablesを復活
  src/bcdiceCore.rb
  src/cgiDiceBot.rb
Labels: bug

#141 CgiDiceBotも乱数詳細を返すように
  src/cgiDiceBot.rb
Labels: 新機能

#146 Fix Rubocop TODOs
  .rubocop.yml
  .rubocop_todo.yml
  src/bcdiceGui.rb
  src/diceBot/Alsetto.rb
  src/diceBot/Amadeus.rb
  src/diceBot/Amadeus_Korean.rb
  src/diceBot/BattleTech.rb
  src/diceBot/BlindMythos.rb
  src/diceBot/BloodCrusade.rb
  src/diceBot/BloodMoon.rb
  src/diceBot/CardRanker.rb
  src/diceBot/ColossalHunter.rb
  src/diceBot/DarkDaysDrive.rb
  src/diceBot/DeadlineHeroes.rb
  src/diceBot/DiceBot.rb
  src/diceBot/Dracurouge.rb
  src/diceBot/Dracurouge_Korean.rb
  src/diceBot/Elysion.rb
  src/diceBot/GardenOrder.rb
  src/diceBot/HatsuneMiku.rb
  src/diceBot/HouraiGakuen.rb
  src/diceBot/HuntersMoon.rb
  src/diceBot/Kamigakari.rb
  src/diceBot/KanColle.rb
  src/diceBot/KillDeathBusiness.rb
  src/diceBot/KillDeathBusiness_Korean.rb
  src/diceBot/KurayamiCrying.rb
  src/diceBot/LostRoyal.rb
  src/diceBot/MagicaLogia.rb
  src/diceBot/Nuekagami.rb
  src/diceBot/Oukahoushin3rd.rb
  src/diceBot/ShinMegamiTenseiKakuseihen.rb
  src/diceBot/ShoujoTenrankai.rb
  src/diceBot/Skynauts.rb
  src/diceBot/TunnelsAndTrolls.rb
  src/diceBot/_Template.rb
  src/irc/ircBot.rb
  src/test/DiceBotTest.rb
Labels: refactoring
