Repository bcdice/BCDice, pull requests merged in 2021-04, with the labels that each got.

#409 先輩後輩TRPG エネカデットに対応
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/Ainecadette.rb
  test/data/Ainecadette.toml
Labels: new dicebot

#447 Command::Parserでコマンドの前後の数値をパースできるようにする
  lib/bcdice/command/parsed.rb
  lib/bcdice/command/parser.y
  test/test_command_parser.rb
Labels: 新機能

#444 [LiveraDoll] リファクタリング
  lib/bcdice/game_system/LiveraDoll.rb
  test/data/LiveraDoll.toml
Labels: refactoring

#446 BattleTech: BTコマンドの結果に成功/失敗を設定する
  lib/bcdice/game_system/BattleTech.rb
  test/data/BattleTech.toml
Labels: enhance dicebot
