Repository bcdice/BCDice, pull requests merged in 2021-05, with the labels that each got.

#452 BattleTech: PPCコマンドを修正する
  lib/bcdice/game_system/BattleTech.rb
  test/data/BattleTech.toml
Labels: bug

#445 BattleTech: CDxコマンドを改良する
  lib/bcdice/game_system/BattleTech.rb
  test/data/BattleTech.toml
Labels: enhance dicebot

#456 BattleTech: PPCコマンドの構文解析を修正する
  lib/bcdice/game_system/BattleTech.rb
  test/data/BattleTech.toml
Labels: bug

#469 NinjaSlayer: repeatコマンド使用時のバグを修正する
  lib/bcdice/common_command/barabara_dice/node.rb
  lib/bcdice/common_command/barabara_dice/result.rb
  lib/bcdice/game_system/NinjaSlayer.rb
  test/data/NinjaSlayer.toml
Labels: bug

#470 BattleTech: Randomizer#rand_results を使わない
  lib/bcdice/game_system/BattleTech.rb
Labels: bug

#403 ダイスボットの作り方のドキュメントを3.0.0対応にする
  .rubocop.yml
  README.md
  docs/how_to_make_dicebot.md
  example/OnseTool.rb
  example/OnseTool.toml
  example/Template.rb
Labels: document

#450 [GranCrest] リファクタリング
  lib/bcdice/game_system/GranCrest.rb
  test/data/GranCrest.toml
Labels: refactoring
