Repository bcdice/BCDice, pull requests merged in 2022-11, with the labels that each got.

#579 [FutariSousa] ヘルプメッセージにイベント表の記載漏れを追記
  lib/bcdice/game_system/FutariSousa.rb
Labels: 誤植修正

#582 [SajinsenkiAGuS] 砂塵戦機アーガス を追加
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/SajinsenkiAGuS.rb
  test/data/SajinsenkiAGuS.toml
Labels: new dicebot

#580 [TorgEternity]高揚(UP)コマンドに修正値指定が出来るように拡張
  lib/bcdice/game_system/TorgEternity.rb
  test/data/TorgEternity.toml
Labels: 変更

#584 Update rubocop to 1.39
  .rubocop_todo.yml
  Gemfile
  lib/bcdice/game_system/AngelGear.rb
  lib/bcdice/game_system/AnimaAnimus.rb
  lib/bcdice/game_system/BeastBindTrinity.rb
  lib/bcdice/game_system/BeginningIdol.rb
  lib/bcdice/game_system/BeginningIdol2022.rb
  lib/bcdice/game_system/BladeOfArcana.rb
  lib/bcdice/game_system/Cthulhu7th_ChineseTraditional.rb
  lib/bcdice/game_system/Cthulhu7th_Korean.rb
  lib/bcdice/game_system/DeadlineHeroes.rb
  lib/bcdice/game_system/EmbryoMachine.rb
  lib/bcdice/game_system/GURPS.rb
  lib/bcdice/game_system/GehennaAn.rb
  lib/bcdice/game_system/LostRoyal.rb
  lib/bcdice/game_system/OracleEngine.rb
  lib/bcdice/game_system/Raisondetre.rb
  lib/bcdice/game_system/RokumonSekai2.rb
  lib/bcdice/game_system/ShinkuuGakuen.rb
  lib/bcdice/game_system/StellarLife.rb
  lib/bcdice/game_system/StrangerOfSwordCity.rb
  lib/bcdice/game_system/TherapieSein.rb
  lib/bcdice/game_system/Torg.rb
  lib/bcdice/game_system/TorgEternity.rb
  lib/bcdice/game_system/cthulhu7th/full_auto.rb
  lib/bcdice/game_system/filled_with/tresure_tables.rb
Labels: refactoring

#585 失敗時のSL0表示を+0から-0に修正
  lib/bcdice/game_system/Warhammer4.rb
  test/data/Warhammer4.toml
Labels: 変更

#587 [CyberpunkRed] 判定コマンドの比較記号の誤りを修正
  lib/bcdice/game_system/CyberpunkRed.rb
  test/data/CyberpunkRed.toml
Labels: bug

#588 [ShinobiGami] ファンブル表の内容を改訂版に変更
  lib/bcdice/game_system/ShinobiGami.rb
  test/data/ShinobiGami.toml
Labels: 変更
