Repository bcdice/BCDice, pull requests merged in 2023-02, with the labels that each got.

#599 ブラドリウムに対応
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/Bloodorium.rb
  test/data/Bloodorium.toml
Labels: new dicebot

#594 「ダンジョンズ＆ドラゴンズ第５版」のダイスボット追加
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/DungeonsAndDragons5.rb
  test/data/DungeonsAndDragons5.toml
Labels: new dicebot

#600 [ShinobiGami] 怪変調表の誤植を修正
  lib/bcdice/game_system/ShinobiGami.rb
Labels: 誤植修正

#601 [SkynautsBouken] 航行イベント表を追加
  lib/bcdice/game_system/SkynautsBouken.rb
  test/data/SkynautsBouken.toml
Labels: enhance dicebot
