Repository bcdice/BCDice, pull requests merged in 2023-03, with the labels that each got.

#602 [HatsuneMiku] 初音ミクTRPG 表追加
  lib/bcdice/game_system/HatsuneMiku.rb
  test/data/HatsuneMiku.toml
Labels: 新機能

#606 [Bloodorium] DCで2桁以上のダイスを指定できない問題を修正
  lib/bcdice/game_system/Bloodorium.rb
  test/data/Bloodorium.toml
Labels: bug

#607 [SkynautsBouken] 航行イベント表　困難系の誤植を修正
  lib/bcdice/game_system/SkynautsBouken.rb
Labels: 誤植修正

#609 [CyberpunkRed] 判定のヘルプメッセージを修正
  lib/bcdice/game_system/CyberpunkRed.rb
Labels: 誤植修正

#611 ワールドエンドフロントライン を追加
  lib/bcdice/game_system.rb
  lib/bcdice/game_system/WorldsEndFrontline.rb
  test/data/WorldsEndFrontline.toml
Labels: new dicebot
